# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_path',
        ),
    ]
