# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20180402_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('-updated',)},
        ),
    ]
