# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20180405_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='groupcart',
            name='store',
        ),
        migrations.RemoveField(
            model_name='groupcartmember',
            name='group_cart',
        ),
        migrations.RemoveField(
            model_name='groupcartmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='group_cart',
        ),
        migrations.DeleteModel(
            name='GroupCart',
        ),
        migrations.DeleteModel(
            name='GroupCartMember',
        ),
    ]
