# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20180407_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={},
        ),
        migrations.AlterModelTable(
            name='partner',
            table='partner',
        ),
    ]
