# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20180407_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='price_currency',
            new_name='unit_price_currency',
        ),
        migrations.AddField(
            model_name='orderline',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stores.Order'),
        ),
    ]
