# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 10:43
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20180503_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='food_container_charge',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
