# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20180503_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='food_container_charge',
            new_name='bowl_charge',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='food_container_charge_currency',
            new_name='bowl_charge_currency',
        ),
    ]
