# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouporder', '0002_auto_20180408_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(choices=[('in', 'IN - currently active'), ('out', 'OUT - exited by user')], default='out', max_length=32),
        ),
    ]
