# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcart',
            name='locked',
        ),
        migrations.AddField(
            model_name='groupcart',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Locked')], default=1, max_length=32),
        ),
    ]
