# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcartmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='groupcartmember',
            name='phone',
        ),
        migrations.AddField(
            model_name='groupcartmember',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='groupcartmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_carts', to=settings.AUTH_USER_MODEL),
        ),
    ]
