# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 00:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dietary_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'Gluten Free'), (1, 'Dairy Free'), (2, 'Vegan'), (3, 'Paleo')], null=True), size=None),
        ),
        migrations.AlterField(
            model_name='menu',
            name='label',
            field=models.IntegerField(choices=[(0, 'Menu'), (1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Weekend Special')], default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
