# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-31 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_remove_image_thumbnail_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
