# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_auto_20171118_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidemenu',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='side_menus', to='lunch.Item'),
            preserve_default=False,
        ),
    ]
