# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 00:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_auto_20180302_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcartmember',
            name='cart',
            field=jsonfield.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
