# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_sidemenu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Local Gems'), (2, 'Continental'), (3, 'Our Picks'), (4, "Today's Special"), (5, "Tomorrow's Special"), (6, 'Fruits and Drinks')], null=True),
        ),
    ]
