# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 14:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'Local gems'), (2, 'Continental'), (3, 'Our Picks'), (4, "Today's Special"), (5, "Tomorrow's Special"), (6, 'Fruits and Drinks')], null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='dietary_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'Gluten Free'), (1, 'Dairy Free'), (2, 'Vegan'), (3, 'Paleo')], null=True), blank=True, null=True, size=None),
        ),
    ]
