# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_auto_20180113_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('metadata', jsonfield.fields.JSONField(blank=True, null=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'menu_options',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='label',
        ),
        migrations.AddField(
            model_name='menuoption',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Menu'),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.OptionGroup'),
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='menus',
            field=models.ManyToManyField(related_name='options', through='lunch.MenuOption', to='lunch.Menu'),
        ),
        migrations.AlterUniqueTogether(
            name='menuoption',
            unique_together=set([('menu', 'option_group')]),
        ),
    ]
