# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_auto_20180302_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcart',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Locked')], default=1),
        ),
    ]
