# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_auto_20180302_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='group_cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='lunch.GroupCart'),
        ),
    ]
