# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('lunch', '0005_auto_20180113_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=19),
        ),
    ]
