# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_auto_20180121_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
