# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 04:14
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_auto_20171125_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='dietary_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'Gluten Free'), (1, 'Dairy Free'), (2, 'Vegan'), (3, 'Vegetarian'), (4, 'Halal')], null=True), blank=True, null=True, size=None),
        ),
    ]
