# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0006_auto_20171126_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='slug',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='itemimage',
            old_name='slug',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='slug',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='slug',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='sideitem',
            old_name='slug',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='sidemenu',
            old_name='slug',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(max_length=64),
        ),
    ]
