# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0006_auto_20180113_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lunch.Payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Online')], default=1),
        ),
    ]
