# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0007_auto_20171126_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidemenu',
            name='multi_select',
            field=models.BooleanField(default=True),
        ),
    ]
