# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lunch', '0007_auto_20180114_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCartMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('metadata', jsonfield.fields.JSONField(blank=True, null=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('cart', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group_cart_member',
            },
        ),
        migrations.RemoveField(
            model_name='groupcartmembers',
            name='group_cart',
        ),
        migrations.RemoveField(
            model_name='groupcartmembers',
            name='user',
        ),
        migrations.AlterField(
            model_name='groupcart',
            name='monetary_limit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='NGN', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='groupcart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_order', to='lunch.Order'),
        ),
        migrations.AlterField(
            model_name='groupcart',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lunch.Payment'),
        ),
        migrations.DeleteModel(
            name='GroupCartMembers',
        ),
        migrations.AddField(
            model_name='groupcartmember',
            name='group_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='lunch.GroupCart'),
        ),
        migrations.AddField(
            model_name='groupcartmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_carts', to=settings.AUTH_USER_MODEL),
        ),
    ]
