# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0008_auto_20180121_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
