# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0009_auto_20180121_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcart',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
