# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0009_auto_20180114_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcart',
            name='token',
        ),
    ]
