# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0010_auto_20171218_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='extras',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.ManyToManyField(related_name='related_orders', to='lunch.Option'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
