# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0010_groupcart_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcart',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_source',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Online')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Failed')], default=1),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
