# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 14:47
from __future__ import unicode_literals

from django.db import migrations
import sendhut.utils
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('lunch', '0011_auto_20171218_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=sendhut.utils.image_upload_path),
        ),
        migrations.AddField(
            model_name='partner',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
