# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0011_auto_20180217_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='payment',
        ),
    ]
