# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0012_auto_20180217_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
