# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 15:55
from __future__ import unicode_literals

from django.db import migrations
import sendhut.utils
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0012_auto_20171230_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='banner',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=sendhut.utils.image_upload_path),
        ),
    ]
