# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0014_auto_20180217_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
