# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0016_auto_20180217_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcart',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='group_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lunch.GroupCart'),
        ),
    ]
