# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0021_auto_20180219_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='group_cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lunch.GroupCart'),
        ),
    ]
