# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20180410_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-updated',)},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Waiting for confirmation'), ('confirmed', 'Confirmed'), ('refunded', 'Refunded'), ('ERROR', 'Rejected')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Draft'), ('unfulfilled', 'Unfulfilled'), ('partially fulfilled', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled'), ('processing', 'Canceled'), ('processing', 'Processing'), ('transit', 'Transit')], default='pending', max_length=32),
        ),
    ]
