# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grouporder', '0002_auto_20180408_0247'),
        ('checkout', '0004_auto_20180410_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='grouporder.GroupOrder'),
        ),
    ]
