# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import sendhut.utils


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_group_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='time_window_end',
            field=models.DateTimeField(default=sendhut.utils.asap_delivery_estimate),
        ),
        migrations.AddField(
            model_name='order',
            name='time_window_start',
            field=models.DateTimeField(default=sendhut.utils.asap_delivery_estimate),
        ),
    ]
