# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20180412_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
