# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0002_coupon_redeemed_at'),
        ('checkout', '0009_auto_20180611_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='giveaways.Coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='group_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='grouporder.GroupOrder'),
        ),
    ]
