# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180612_1257'),
        ('checkout', '0010_auto_20180611_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Address'),
            preserve_default=False,
        ),
    ]
