# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_window_end',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_window_start',
        ),
    ]
