# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-15 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import sendhut.utils


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20180612_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=sendhut.utils.asap_delivery_estimate),
        ),
    ]
