# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_order_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
    ]
