# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0003_auto_20180612_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='state',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='status',
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='token',
        ),
    ]
