# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='slug',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='slug',
            new_name='uuid',
        ),
    ]
