# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180218_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
    ]
