# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 17:03
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171211_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
