# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180607_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='apt',
            new_name='building_number',
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
