# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='building_number',
            new_name='building_name',
        ),
    ]
