# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171218_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='invite_token',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='allowance',
            name='name',
            field=models.CharField(blank=True, default="b'd7a2cb1aa2620900b42'-LightSlateGray-Heath-Wall", max_length=100, null=True),
        ),
    ]
