# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171218_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='name',
            field=models.CharField(blank=True, default="b'aad18fa437c28ca65ba'-Sienna-Shelley-Run", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
