# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20171218_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='name',
            field=models.CharField(blank=True, default="b'2493abe83e0ef224528'-DarkGreen-Joan-Run", max_length=100, null=True),
        ),
    ]
