# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20171218_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='name',
            field=models.CharField(blank=True, default="b'7aeea65ecab8944468a'-GhostWhite-Swanson-Summit", max_length=100, null=True),
        ),
    ]
