# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20171218_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='name',
            field=models.CharField(blank=True, default="b'ea9576e96ad0acce5e1'-Beige-Sophia-Loaf", max_length=100, null=True),
        ),
    ]
