# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20180607_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='order',
        ),
    ]
